# Generated by Django 3.2.16 on 2022-12-27 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Data inicio')),
                ('excel_file', models.FileField(upload_to='', verbose_name='Excel Para Leitura')),
                ('path_to_manage', models.FilePathField()),
                ('path_to_find', models.FilePathField()),
                ('user_exe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Usuarios', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
