# Generated by Django 3.2.16 on 2022-12-27 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reader',
            name='excel_file',
        ),
        migrations.RemoveField(
            model_name='reader',
            name='path_to_find',
        ),
        migrations.RemoveField(
            model_name='reader',
            name='path_to_manage',
        ),
    ]
