# Generated by Django 3.2.16 on 2022-12-27 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20221227_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='excel_file',
            field=models.FileField(blank=True, default='', upload_to='', verbose_name='Excel Para Leitura'),
        ),
        migrations.AddField(
            model_name='reader',
            name='path_to_find',
            field=models.FilePathField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='reader',
            name='path_to_manage',
            field=models.FilePathField(blank=True, default=''),
        ),
    ]
