# Generated by Django 3.2.16 on 2022-12-27 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20221227_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='path_to_manage',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
