# Generated by Django 3.2.16 on 2022-12-27 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_alter_reader_path_to_manage'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='status',
            field=models.CharField(default='Criado', max_length=15),
        ),
    ]
