# Generated by Django 3.2.16 on 2022-12-28 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_reader_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='path_files',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
